### ISSUE TITLE
super 身份查看用户列表出错

### ISSUE THREAD

**Issue by runzx** [TaleLin/lin-cms-koa#1]
error_code: 999
msg: "服务器未知错误"
url: "/cms/admin/users?count=10&page=0"

super 用户没有定义group_id ，所以查询时要考虑此情况。

**Comment by PedroGao** [comment]
ok，多谢啊，马上去改正

**Comment by PedroGao** [comment]
刚没看清楚，这里的设计是没有问题的，super用户作为超级管理员，本来就不被纳入到管理中，他是唯一存在的，超然所有的。

**Comment by runzx** [comment]
问题是你用super 查看用户列表时出错，不能列表，因为你后台查询时要group_id

**Comment by PedroGao** [comment]
group_id是可以为空的啊，默认为空就是所有分组，我们还是会根据admin字段来排除super用户的
