### ISSUE TITLE
文件上传接口上传小图片会提示超时

### ISSUE THREAD

**Issue by ChenJinchuang** [TaleLin/lin-cms-koa#104]
**描述 bug**
调用文件上传接口的图片小于一定大小的话，会报接口超时。
- 你是如何操作的？
使用lin-cms-vue的图片上传组件示例组件上传一张20多k的图片和111k的图片
- 发生了什么？
20多K的图片会提示接口超时，111k的正常，可重复复现
- 你觉得应该出现什么？
都提示上传成功

**你使用哪个版本出现该问题？**
lin-cms-vue/master   
lin-cms-koa/master

**如何再现**

使用lin-cms-vue的图片上传组件示例组件上传一张大于等于80k的图片会提示成功；上传一张小于等于40k的会提示接口超时。其余大小自行观察。

**Comment by OtOliu** [comment]
图片上传，图片大小为13.4k上传提示请求超时
![image](https://user-images.githubusercontent.com/36293627/101735326-b18e6180-3afc-11eb-8c24-24d9de71abb3.png)
图片大小为166k上传成功

**Comment by ChenJinchuang** [comment]
> 图片上传，图片大小为13.4k上传提示请求超时
> ![image](https://user-images.githubusercontent.com/36293627/101735326-b18e6180-3afc-11eb-8c24-24d9de71abb3.png)
> 图片大小为166k上传成功

破案了，Node.js版本问题。尝试切换Node 12 版本

**Comment by whwnow** [comment]
同样遇到这个问题，我现在的node版本是 14.15.1，下面是上传报错的图片。
需要我降级到 12 解决问题么？
![20210111](https://user-images.githubusercontent.com/1713701/104334395-44238580-552d-11eb-91c2-3cea4b84d000.jpeg)

**Comment by ChenJinchuang** [comment]
> 同样遇到这个问题，我现在的node版本是 14.15.1，下面是上传报错的图片。
> 必须降级到 12 才能解决么？现在官网都没 12 的下载地址了……
> ![20210111](https://user-images.githubusercontent.com/1713701/104334395-44238580-552d-11eb-91c2-3cea4b84d000.jpeg)

阿里云有代理镜像，啥版本都有。或者装一个 nvm

**Comment by smileShirmy** [comment]
升级 lin-mizar 版本可以解决这个问题，项目根目录下执行 `npm install lin-mizar@0.3.9`

**Comment by shuax** [comment]
0.3.9依然有这个问题，修改用户头像。

**Comment by shuax** [comment]
https://github.com/m4nuC/async-busboy/issues/49
按照这个改，可以用了。
