### ISSUE TITLE
lin-mizar包的作用以及用法

### ISSUE THREAD

**Issue by 13640134627** [TaleLin/lin-cms-koa#105]
我是node新人，在学习项目的过程中对lin-mizar这个包的引入以及作用感到非常疑惑。
在文档中也没有介绍到lin-mizar，而我使用LinRouter的时候总是抛出CodeMessage.getMessage() must be implemented的错误信息，所以卡壳在这里了。
希望可以简单介绍下lin-mizar。

**Comment by smileShirmy** [comment]
lin-mizar 是 lin-cms-koa 的一个核心库，主要封装了路由视图，参数校验，异常处理，文件处理，你报的这个错可能是没有升级到最新的版本，请确保 lin-cms-koa 是最新的 master 分支

**Comment by 13640134627** [comment]
好的
