### ISSUE TITLE
快速上手的文档部分建议。

### ISSUE THREAD

**Issue by liicos** [TaleLin/lin-cms-koa#107]
![image](https://user-images.githubusercontent.com/29332099/102316808-9797c780-3fb1-11eb-8082-05e9a3ad9fae.png)
后端快速上手的文档写的乱七八糟稀巴烂，这些模块不用引入就能直接调用？跟随这个教程真的能走得通？

**Comment by smileShirmy** [comment]
抱歉，关于这个问题，这个月会重新梳理并完善文档
