### ISSUE TITLE
有办法用vscode 进行debugger调试吗？launch.json应该怎么配置呢？

### ISSUE THREAD

**Issue by CIGE-Vince** [TaleLin/lin-cms-koa#109]
{
    // 使用 IntelliSense 了解相关属性。
    // 悬停以查看现有属性的描述。
    // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [{
      "type": "node",
      "request": "launch",
      "name": "启动程序",
      "program": "${workspaceFolder}\\zhuangyaozi\\lin-cms-koa\\app\\app.js",
      "runtimeExecutable": "nodemon", // 或者 node-dev
      "restart": true,
      "console": "integratedTerminal",
      "skipFiles": [
        "${workspaceRoot}/node_modules/**/*.js",
        "<node_internals>/**/*.js"
      ]
    }]
  }

我这样配置会因为node不支持es6语法导致报错。我看到项目用的是babel7，这个应该如何配置？

**Comment by smileShirmy** [comment]
把 program 的地址改为当前项目根目录下的 index.js "program": "${workspaceFolder}\\index.js",
