### ISSUE TITLE
ctx.multipart()  上传文件不返回上传路径吗

### ISSUE THREAD

**Issue by CIGE-Vince** [TaleLin/lin-cms-koa#111]
const files = await ctx.multipart();

我要如何获得文件上传的本地路径?

**Comment by CIGE-Vince** [comment]
@lucienstar 能帮忙解决下疑问吗？对接阿里云的local-file
  let stream = fs.createReadStream('local-file');
  let result = await client.putStream('object-name', stream);

**Comment by smileShirmy** [comment]
上传成功后返回的字段中有 `path` 和 `url` 都是上传的文件在服务器中的路径。如果你想得到前端上传的文件路径这得要把文件路径在前端传到服务端。
