### ISSUE TITLE
关于jwt的secret的疑问？

### ISSUE THREAD

**Issue by blogwy** [TaleLin/lin-cms-koa#131]
请详细描述您对本项目的任何问题，我们会在第一时间查阅和解决。
在`secure.js`文件里面有个secret，为啥是“\x88W\xf09\x91\x07\x98\x89\x87\x96\xa0A\xc68\xf9\xecJJU\x17\xc5V\xbe\x8b\xef\xd7\xd8\xd3\xe6\x95*4”这种格式。jwt secret不是随便一个字符串就行了吗？

**Comment by vanoneang** [comment]
可以的，自己定义一组字符串就行了。
