### ISSUE TITLE
现在不允许统一传参的方式修改status的状态码的吗？

### ISSUE THREAD

**Issue by lgjdream** [TaleLin/lin-cms-koa#134]
请详细描述您对本项目的任何问题，我们会在第一时间查阅和解决。
![111111111111111111111111](https://user-images.githubusercontent.com/29623835/138012899-4c6c68f1-d99f-40eb-b91b-177908004f4e.png)

**Comment by smileShirmy** [comment]
成功就不用抛出异常了吧，本项目都是遵循HTTP规范的，如果是200就不需要抛出异常，有异常都是500之类的
