### ISSUE TITLE
debug设置为false后，仍然有日志输出

### ISSUE THREAD

**Issue by freekingg** [TaleLin/lin-cms-koa#136]
debug: false,

debug设置为false后，仍然有日志输出

![图像 44](https://user-images.githubusercontent.com/23447622/153752507-447f9f73-4de3-4c6c-91ee-61bf129b0be7.png)

**Comment by sunshineroper** [comment]
把配置文件  `log: {requestLog: false}`

**Comment by smileShirmy** [comment]
这里的 debug 指的是生产环境的 debug，具体可以看代码，不是指开发环境的输出
