### ISSUE TITLE
user模型扩展字段无法写入数据

### ISSUE THREAD

**Issue by wlf36** [TaleLin/lin-cms-koa#21]
![image](https://user-images.githubusercontent.com/12623898/60066388-8ca40400-9739-11e9-844c-d93ffc25222a.png)
![image](https://user-images.githubusercontent.com/12623898/60066414-aa716900-9739-11e9-954a-5a7749861354.png)
![image](https://user-images.githubusercontent.com/12623898/60066442-c96ffb00-9739-11e9-9f36-b2d3c5fbe4b5.png)

**Comment by PedroGao** [comment]
sequelize升级了v5版，使一些东西出现了变化，正在抓紧修复，抱歉了。

**Comment by PedroGao** [comment]
已经修复了，记得更新一下依赖 lin-mizar 的版本为 0.1.0-beta4。
所有更新已经更到了master分支上，模型扩展的方法见[user.js](https://github.com/TaleLin/lin-cms-koa/blob/master/app/models/user.js)
