### ISSUE TITLE
lin-validator中，判断是否为async失效，导致在校验层中抛出异常没有经过中间件

### ISSUE THREAD

**Issue by ontheroad1992** [TaleLin/lin-cms-koa#28]
**在校验层中自定义校验方法，抛出异常无法被koa捕捉**

- 在校验层中定义了一个 async validateXXXX 的校验方法
![7`6I2~{4Z89Q_LF655RGGM4](https://user-images.githubusercontent.com/29194619/61196437-3c4d1000-a701-11e9-8a2d-176e126d4769.png)
- validateXXXX抛出异常后，并没有经过koa中间件捕捉，错误直接抛出
![XI0_HCGTSRR0~ A_RVN3GEH](https://user-images.githubusercontent.com/29194619/61196521-d9a84400-a701-11e9-96a3-ff9539ccacd4.png)

**版本信息**
- windows10 x64
- node.js v10.15.0 x64
- lin-mizar 0.1.0-beta.4

**错误原因**
查看了 lin-mizar 源码后，发现 is-async-function 判断错误
![}LY)$ 1ODSSJFLKE_L{} WM](https://user-images.githubusercontent.com/29194619/61196642-a7e3ad00-a702-11e9-99f2-b79594f16263.png)

临时解决，只用于测试
![image](https://user-images.githubusercontent.com/29194619/61196655-c649a880-a702-11e9-85c5-bfc39db7eaaf.png)

**Comment by PedroGao** [comment]
知道了，会尽快排查修复的，谢谢帮忙找到了问题原因。

**Comment by PedroGao** [comment]
更新 lin-mizar 版本为 0.1.0-beta.5
