### ISSUE TITLE
关于异常处理返回的error_code的命名疑问

### ISSUE THREAD

**Issue by ontheroad1992** [TaleLin/lin-cms-koa#34]
我很喜欢目前的http状态设置，但是对于‘正确的请求201’和异常请求的body字段中，自定义的状态码键值都使用‘error_code’的设置，感觉从语义上来讲有点多此一举的感觉，根绝现在项目的规范，http的Status字段已经标明当前的请求的大致情况，为何还要在body中在重复声明这是个什么类型的自定义code。
例如：400是一个错误的请求，但返回的body中为何还要用 error_code 即为错误的状态码，两次出现错误这种就感觉重复啰嗦了，并且在内置的 Success 这个对象中也用 error_code 是不有点不妥；
建议：在HttpException中将字段code改为status,error_code改为code，这样在返回的消息中层次分明，status就能标明当前的请求是什么情况，而code也能具体到某些业务的情况，

**Comment by vanoneang** [comment]
感谢关注，我们会讨论下
