### ISSUE TITLE
关于路由URL的一个小bug

### ISSUE THREAD

**Issue by ToWeLong** [TaleLin/lin-cms-koa#36]
**描述 bug**

举个例子：我设计了一个 /v1/book/:id 接口 并用对id进行了参数校验，就是id不能为空
然后我又设计了一个 /v1/book/list 接口  接下来就报错了  用GET请求访问 也会返回错误 也提示id不能为空

**Comment by ontheroad1992** [comment]
不太清除你的设置，但从字面意思上来看，因为 /v1/book/:id 和 /v1/book/list 如果都是同样的请求方式，那么会优先匹配 /v1/book/:id，至于你 Id 怎么传参的久不太清除了，如果你是想设计一个 list 的接口，那么直接 /v1/book 就行了

**Comment by PedroGao** [comment]
这个并非bug，而是koa-router的设计本身就不能支持这样模糊的路由
