### ISSUE TITLE
数据库无法自动创建数据表

### ISSUE THREAD

**Issue by runfi** [TaleLin/lin-cms-koa#39]
初次初始化项目，运行add_super.js后，创建了表
**lin_auth**
**lin_file**
**lin_group**
**lin_log**
**lin_user**
但是没有创建表 book
问题：
1、如果不存在表book，则无法运行文档中所说的fake_book.js
2、是否有配置项可配置由 Book.init 自动创建book表
3、如果有，请问在哪里

**Comment by vanoneang** [comment]
sequelize需要使用模型才会自动创建数据表，book表如果已经下载的源码中，有相关book的api部分，应该是可以自动生成的，

如果是添加新的业务模型（表），需要先在api文件夹下创建相应的控制器并引用这个模型
