### ISSUE TITLE
你好，请问下findAll中where下的delete_time可以写成deleteTime吗

### ISSUE THREAD

**Issue by KDWangBoss** [TaleLin/lin-cms-koa#43]
我在lin-mizar/lin/interface中的InfoCrudMixin添加了underscored:true，这里的驼峰应该映射了数据库的下划线，在查询的时候如果写成deleteTime为什么不会被映射为delete_time呢

**Comment by PedroGao** [comment]
findAll{}执行的参数是会以原始文本的形式映射到sql语句的，underscored:true不会作用在这个地方

**Comment by KDWangBoss** [comment]
明白了，感谢答复
