### ISSUE TITLE
官方文档文案错误

### ISSUE THREAD

**Issue by shenxiang11** [TaleLin/lin-cms-koa#44]
url：http://doc.cms.7yue.pro/lin/server/koa/authority_model.html#%E6%9D%83%E9%99%90%E7%AE%A1%E7%90%86

> 请在 postman 的 url 地址栏输入http://127.0.0.1:5000/cms/user/login，请求方法选 择 post 方法，并在请求参数的 body 里面填入下面数据：

```json
{
  "nickname": "super", // 此处应该是 username
  "password": "123456"
}
```

**Comment by PedroGao** [comment]
十分抱歉，因为业务更改的原因，文档没有及时更新，现在应该好了
