### ISSUE TITLE
validate(ctx) bug

### ISSUE THREAD

**Issue by runzx** [TaleLin/lin-cms-koa#5]
https://github.com/TaleLin/lin-cms-koa/blob/12a02f397c2d4866a0f46793d37f87d1159bd097/app/api/v1/book.js#L31

改： 
```
bookApi.get("/:id", async ctx => {  
  const v = await new PositiveIdValidator().validate(ctx);
```

**Comment by PedroGao** [comment]
已经修复提交了，最近升级大版本了，不好意思
