### ISSUE TITLE
lin-mizar 0.2.3安装报错

### ISSUE THREAD

**Issue by wangyuan0108** [TaleLin/lin-cms-koa#55]
lin-mizar 0.2.3安装报错；
![image](https://user-images.githubusercontent.com/22407253/69109912-0f947500-0ab4-11ea-9444-12435ebb1e23.png)

**Comment by vanoneang** [comment]
先别用淘宝镜像，用npm试试，淘宝那边0.2.3还没同步过去

**Comment by wangyuan0108** [comment]
> 先别用淘宝镜像，用npm试试，淘宝那边0.2.3还没同步过去

好的，我试试
