### ISSUE TITLE
关于koa项目配置项的一些提问

### ISSUE THREAD

**Issue by JokerOfRevenge** [TaleLin/lin-cms-koa#58]
### 关于配置路径灵活性的一些问题
在app/starter.py的文件中。采用了process.cwd()作为配置文件的baseDir。
这意味着，如果我不想改变现有项目的结构，我必须在指定文件夹路径下才能启动项目。

**但是在部署的时候，制作的服务启动脚本其实并不固定，可能会有多种情况（不是在指定文件夹路径下启动脚本）。**

而且在lin的源码中，也有一些process.cwd()作为baseDir的地方（读取apiDir和加载plugin的configDir）。这就直接导致了只能在指定位置启动项目。

_同时：配置log文件夹的路径就没有采用这种baseDir的获取方式，我可以直接写一个绝对路径进去直接指定到我想要的位置。_ 

同样都是配置文件，但是出现了两种不同的配置思维和风格。为了保持配置的灵活性，这些baseDir是否在版本迭代的过程中也放开维护或是采用更灵活的方式而不是直接默认执行启动脚本的路径。

**Comment by vanoneang** [comment]
感谢反馈，后续版本会处理这个问题
