### ISSUE TITLE
validator 的 isEmpty 和 isNotEmpty 问题

### ISSUE THREAD

**Issue by zaxlct** [TaleLin/lin-cms-koa#62]
**描述 bug**
我用的慕课网 koa 实战课程里源码里的 `lin-validator`，非 NPM 下载。
```
this.content = [new Rule('isNotEmpty', '内容不能为空')]
```
lin-koa 文档示例用的是 `isNotEmpty`，但是会报错 validator.js 没有 isNotEmpty 方法。我查了
validator.js  文档，他们有 `isEmpty`，但是没有 `isNotEmpty`

**你使用哪个版本出现该问题？**
第二个问题，如何用 npm 安装 `LinValidator`
我看源码用 npm 安装 `lin-mizar` ，

```
const { LinValidator, Rule } = require('lin-mizar')
```

结果又报错：
`Error: Dialect needs to be explicitly supplied as of v4.0.0`

**Comment by smileShirmy** [comment]
慕课网 koa 实战课程中的 lin-validator 依赖的库是 validator 这个库，这个库确实没有 `isNotEmpty`。但是 lin-mizar 里面依赖的库是 class-validator，因此 lin-cms 有。另外这个 lin-mizar 是配合 lin-cms-koa 来使用的，不能单独这样安装来使用。

我的建议是不用 `isNotEmpty`，你可以使用 `isLength` 之类的方式替代之。
