### ISSUE TITLE
关于 lin-mizar 的文档

### ISSUE THREAD

**Issue by liicos** [TaleLin/lin-cms-koa#67]
源码中好像很多地方都用了lin-mizar这个库，但是我没有找到lin-mizar这个库的相关文档，http://doc.cms.7yue.pro/lin/server/ 上面也没有讲相关的内容，感觉文档写的很糟糕。

**Comment by vanoneang** [comment]
lin-cms-koa-core 在仓库 docs 目录下，用 typedoc 生成的有简易文档
