### ISSUE TITLE
抱歉，我有一个扩展性问题想的不是很明白，请教下

### ISSUE THREAD

**Issue by tclcm1987** [TaleLin/lin-cms-koa#72]
lin-cms是一个分角色的权限cms管理系统，在koa中实现的原理就是中间件。在lin-cms中lin-user存储的是管理员和系统的操作员账号。那么我如果有一些使用程序前台的终端客户，比如存在myuser表中,那么如果我想为这些用户使用token令牌来验证登录，那么我是不是需要自己构建token系统，以及拓展自己的中间件来控制api的访问权限？可以直接借助lin-cms搭建好的吗？

**Comment by vanoneang** [comment]
可以在 lin-cms 中写入前端逻辑。

1. 前端的 token 系统需要自己构建，返回给客户端；
2. 在 `middleware` 中新增一个中间件，解析前端请求时，headers 携带的 token，解出身份信息挂载到 `ctx` 上；
3. 在接口处，第三个参数选择不挂载权限到数据库，第四个参数选择刚写的中间件
![image](https://user-images.githubusercontent.com/29253688/81132582-86013280-8f81-11ea-8be1-313fce8bf072.png)
