### ISSUE TITLE
运行 node test/helper/fake-book/index.js报错

### ISSUE THREAD

**Issue by josnfei** [TaleLin/lin-cms-koa#74]
**描述 bug**

根据官方文档 koa入门 - 后端快手上手
![image](https://user-images.githubusercontent.com/28798709/83834074-09987580-a720-11ea-85f2-4e9307f5af2e.png)

- 你是如何操作的？
-  运行  node test/helper/fake-book/index.js  报错

**你使用哪个版本出现该问题？**

master 默认分支

- 报错截图如下
![image](https://user-images.githubusercontent.com/28798709/83834244-698f1c00-a720-11ea-9aa2-a8ec91ef8e04.png)

**Comment by vanoneang** [comment]
现在的版本可以直接使用项目根目录下的 `sql` 文件。
