### ISSUE TITLE
关于日志管理模块 出现 “{user.username}编辑了期刊内容” 的回显状态出现了 {user.username} 字符没有转化用户名root的问题。

### ISSUE THREAD

**Issue by liangjuncheng1995** [TaleLin/lin-cms-koa#88]
版本：0.3.8
 "name": "lin-cms-koa",
  "version": "0.3.8",
今天使用koa框架搭建期刊管理的功能，发现日志提交之后，回显异常的问题：
![image](https://user-images.githubusercontent.com/30004721/88158629-df066b80-cc3e-11ea-9cd9-a8d171fdf2d0.png)
看logger的源码：
![image](https://user-images.githubusercontent.com/30004721/88158716-f7768600-cc3e-11ea-84f1-8fb05d8fe9b2.png)
最终在logger.js 定位问题：
![image](https://user-images.githubusercontent.com/30004721/88158912-31478c80-cc3f-11ea-86b5-1d78365dda0e.png)
进入解析模板的函数：
![image](https://user-images.githubusercontent.com/30004721/88159246-9dc28b80-cc3f-11ea-9681-2aeb6be2a5c6.png)
控制台：
![image](https://user-images.githubusercontent.com/30004721/88159277-a9ae4d80-cc3f-11ea-9ec1-554cfad2053a.png)
单独把正则拿出来校验：
const REG_XP = /(?<=\{)[^}]*(?=\})/g
var res = REG_XP.exec("{user.username}编辑了期刊内容")
var res1 = REG_XP.exec("{user.username}编辑了期刊内容")
console.log(res)
console.log(res1)
第二次返回也是 null 的情况。。
![image](https://user-images.githubusercontent.com/30004721/88159415-da8e8280-cc3f-11ea-84b2-668045b64f3b.png)

**Comment by vanoneang** [comment]
感谢反馈，[已处理](https://github.com/TaleLin/lin-cms-koa/commit/e57361fff794ed06479f8b21f70222a284f5ed3e)。
