### ISSUE TITLE
这套框架sequenlize orm如何实现belongsto的association

### ISSUE THREAD

**Issue by xingdavis** [TaleLin/lin-cms-koa#92]
如果要实现一个一对一的关系代码如何写
比如有个Article model,通过外键author_id关联到对应的User 作者
Article.belongsTo(User, { foreignKey: 'author_id', as: 'author',targetKey:'id'})

**Comment by vanoneang** [comment]
可以添加 `constraints: false` 属性，可以解除强制创建外键。

**Comment by xingdavis** [comment]
> 可以添加 `constraints: false` �属性，可以解除强制创建外键。

试过只要指定已经存在的 foreignKey 就可以了

建立association好像按Sequelize文档的标准写就可以，关键是怎样获得嵌套的对象模型输出给前端，得在序列化输出时自己定义好
